Spring Security s+c
mate-academy/jv-spring-security pull request #212
Opened 2022-06-20 06:54 UTC by yuriikozar

Solution + Checkstyle

2022-06-20 13:53 UTC, dopalex approved these changes

2022-06-20 14:20 UTC, KseniiaMakarova requested changes

2022-06-20 14:20 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/controller/CustomGlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
а сюда получится положить не string?

2022-06-20 14:20 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/dto/request/CinemaHallRequestDto.java
>      private String description;
does `max` work with string?

2022-06-20 14:20 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/dto/request/MovieRequestDto.java
>      private String description;
same

2022-06-20 14:20 UTC, KseniiaMakarova commented on src/main/java/mate/academy/spring/dto/request/MovieRequestDto.java
>  public class MovieRequestDto {
your whole validation config does not work now, 1 thing is missing, adding annotations in dtos is not enough

2022-06-20 20:12 UTC, yuriikozar commented on src/main/java/mate/academy/spring/controller/CustomGlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
Там де параметризація String - тільки string
В Object можна покласти будь-що

2022-06-21 08:53 UTC, KseniiaMakarova approved these changes

2024-02-15 18:23 UTC, closed without merging