Spring security implemented
mate-academy/jv-spring-security pull request #340
Opened 2022-12-09 15:51 UTC by pavlogook

2022-12-10 13:48 UTC, YuriiHryniv requested changes

2022-12-10 13:48 UTC, YuriiHryniv commented on src/main/java/mate/academy/spring/config/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
Apparently, you forgot to add this class to WebAppInitializer.
![image](https://user-images.githubusercontent.com/63553735/206858176-6c7e6041-1f5a-4d2e-9066-8950e1dacbe0.png)

2022-12-10 14:37 UTC, YuriiHryniv approved these changes
LGTM!

2022-12-16 09:54 UTC, hronograf requested changes

2022-12-16 09:54 UTC, hronograf commented on src/main/java/mate/academy/spring/config/SecurityConfig.java
> +                .anyRequest().authenticated()
let's add `@Override` annotation
also looks like users can't register themselves

2022-12-16 09:54 UTC, hronograf commented on src/main/java/mate/academy/spring/service/impl/UserServiceImpl.java
>      private static final int SALT_LENGTH = 10;
do we need `SALT_LENGTH` constant?

2022-12-16 10:21 UTC, hronograf approved these changes

2024-12-15 15:08 UTC, closed without merging