Hw spring security
mate-academy/jv-spring-security pull request #409
Opened 2023-02-21 20:45 UTC by DanyloBorysenko

2023-02-22 16:11 UTC, Ivan95kos requested changes

2023-02-22 16:11 UTC, Ivan95kos commented on src/main/java/mate/academy/spring/controller/CustomGlobalExceptionHandler.java
> +    private static final int BAD_REQUEST = 400;
Use already created constants HttpStatus.BAD_REQUEST  HttpStatus.INTERNAL_SERVER_ERROR
```suggestion
```

2023-02-22 16:11 UTC, Ivan95kos commented on src/main/java/mate/academy/spring/exception/AuthenticationException.java
> +public class AuthenticationException extends RuntimeException {
no need to change the extension
```suggestion
public class AuthenticationException extends Exception {
```

2023-02-22 16:11 UTC, Ivan95kos commented on src/main/java/mate/academy/spring/controller/AuthenticationController.java
> +        }
Create your own annotation that will check if passwords match

2023-02-23 14:52 UTC, kozhukhovsky approved these changes

2025-09-15 12:52 UTC, closed without merging